import { CommonModule, DatePipe } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    input,
} from '@angular/core';

import { DocumentInstance } from '@coolms/document-angular';

import { filenameOf, formatLocation, formatSize } from './vfs-location.helpers';

/**
 * Phase A.1b — focused-instance properties panel. Mounts in the right
 * detail slot when `state.rightPanelMode === 'instances'` and an
 * instance is selected. The DocumentDetail dispatcher routes here
 * directly (no per-format split — instance metadata is uniform across
 * formats).
 *
 * Phase D hotfix #2: read-only metadata view. View / Download /
 * Regenerate / Delete live exclusively on the toolbar + right-click
 * context menu surfaces, dispatched through the page handler. The
 * inline action row used to live here too, which produced
 * triple-surfaced action duplication.
 */
@Component({
    selector: 'cms-instance-detail',
    standalone: true,
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [CommonModule, DatePipe],
    template: `
        <article class="cms-instance-detail" [attr.data-selectable]="''">
            <header class="cms-instance-detail__header">
                <h2 [title]="filename()">{{ filename() }}</h2>
            </header>

            <div class="cms-instance-detail__badges">
                <span class="cms-instance-detail__badge cms-instance-detail__badge--format">
                    {{ instance().outputFormat | uppercase }}
                </span>
                <span class="cms-instance-detail__badge"
                      [attr.data-status]="instance().status">
                    {{ instance().status }}
                </span>
            </div>

            <dl class="cms-instance-detail__meta">
                <dt>Location</dt>
                <dd><span class="cms-instance-detail__path">{{ location() }}</span></dd>

                <dt>Size</dt>
                <dd>{{ formattedSize() }}</dd>

                <dt>Template</dt>
                <dd>{{ templateName() ?? '—' }}</dd>

                <dt>Generated by</dt>
                <dd>{{ generatedByLabel() }}</dd>

                <dt>Generated at</dt>
                <dd>
                    @if (instance().generatedAt) {
                        {{ instance().generatedAt | date:'medium' }}
                    } @else {
                        —
                    }
                </dd>

                @if (instance().errorMessage) {
                    <dt>Error</dt>
                    <dd class="cms-instance-detail__error">{{ instance().errorMessage }}</dd>
                }
            </dl>
        </article>
    `,
    styles: [`
        :host {
            display: block;
            height: 100%;
            overflow: auto;
        }
        .cms-instance-detail {
            padding: var(--cms-panel-padding);
        }
        .cms-instance-detail__header {
            display: flex;
            align-items: flex-start;
            justify-content: space-between;
            gap: 8px;
            margin-bottom: 8px;
        }
        .cms-instance-detail__header h2 {
            margin: 0;
            font-size: 1rem;
            font-weight: 500;
            word-break: break-all;
            flex: 1;
            min-width: 0;
        }
        .cms-instance-detail__badges {
            display: flex;
            gap: 6px;
            margin-bottom: var(--cms-content-padding);
        }
        .cms-instance-detail__badge {
            display: inline-block;
            padding: 1px 8px;
            border-radius: var(--cms-radius-sm);
            background: var(--cms-border-light);
            font-size: 0.75rem;
            text-transform: lowercase;
            color: var(--cms-text-secondary);
        }
        .cms-instance-detail__badge--format {
            text-transform: uppercase;
            letter-spacing: 0.04em;
            font-weight: 500;
        }
        .cms-instance-detail__badge[data-status="rendered"] {
            background: rgba(16, 185, 129, 0.12);
            color: rgb(6, 95, 70);
        }
        .cms-instance-detail__badge[data-status="failed"] {
            background: rgba(239, 68, 68, 0.12);
            color: rgb(153, 27, 27);
        }
        .cms-instance-detail__meta {
            display: grid;
            grid-template-columns: max-content 1fr;
            gap: 6px 12px;
            margin: 0;
            font-size: 0.85rem;
        }
        .cms-instance-detail__meta dt {
            color: var(--cms-text-muted);
            font-weight: 500;
        }
        .cms-instance-detail__meta dd {
            margin: 0;
            word-break: break-all;
        }
        .cms-instance-detail__path {
            font-family: var(--cms-font-mono, ui-monospace, SFMono-Regular, monospace);
            font-size: 0.8rem;
            color: var(--cms-text);
            background: var(--cms-border-light);
            padding: 1px 6px;
            border-radius: var(--cms-radius-sm);
        }
        .cms-instance-detail__error {
            color: var(--cms-danger, #b91c1c);
            font-size: 0.8rem;
        }
    `],
})
export class InstanceDetailComponent {
    readonly instance = input.required<DocumentInstance>();

    protected readonly filename = computed(() => {
        const i = this.instance();
        const fallback = i.name && i.name.length > 0
            ? `${i.name}.${i.outputFormat}`
            : `${i.id.slice(0, 8)}.${i.outputFormat}`;
        return filenameOf(i.vfsPath, fallback);
    });

    protected readonly location = computed(() => formatLocation(this.instance().vfsPath));

    /**
     * Read from `templateSnapshot.name` — denormalised on the backend
     * row so the explorer doesn't have to join the live template
     * table. Falls back to the snapshot's `slug` if `name` was empty
     * at generation time.
     */
    protected readonly templateName = computed<string | null>(() => {
        const snap = this.instance().templateSnapshot;
        if (!snap) {
            return null;
        }
        const name = snap['name'];
        if (typeof name === 'string' && name.length > 0) {
            return name;
        }
        const slug = snap['slug'];
        return typeof slug === 'string' ? slug : null;
    });

    /**
     * Phase A.1b backend ops: file size lives on the resource now —
     * provider batch-resolves the VFS node per page. `null` for
     * pending rows or orphans (file gone but row still in DB).
     */
    protected readonly formattedSize = computed(() => formatSize(this.instance().size));

    protected readonly generatedByLabel = computed(() => {
        const name = this.instance().createdByName;
        return name && name.length > 0 ? name : '—';
    });
}
