#!/usr/bin/env node
// The admin's and the app's design tokens, from ONE file: tokens/coolms.tokens.json, so the two
// cannot drift apart (agreed 2026-10-05). Writes:
//
//   angular/src/tokens.generated.scss  the admin's `:root` and `:root[data-theme='dark']` blocks
//   tokens/coolms-tokens.ts            the app's plain-data module, vendored at a pinned commit
//
// Refuses -- writes nothing -- a colour token with neither a dark value nor a stated reason it
// does not flip ("invariant"): a colour that forgot its dark value was invisible until a dark
// panel showed it. The app's module carries what the app can paint (the app's three
// conditions): colours as literal values React Native parses, aliases left out, `dark` complete --
// every key of `light`, an invariant carrying its one value -- and radii as numbers. It leaves out
// the admin's brand accent: the app's accent is the server's, from discovery. Shadows, the font
// stack and the layout sizes are the stylesheet's alone.
//
//   node tools/design-tokens.mjs           write both files
//   node tools/design-tokens.mjs --check   write nothing; exit 1 if either file is not what the
//                                          token file generates (a hand edit, or no regeneration)
//
// Exit: 0 written or current; 1 FOUND -- a token refused, or (--check) a generated file out of
// date; 2 UNEVALUABLE -- the token file could not be read.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = 'tokens/coolms.tokens.json';
const SCSS = 'angular/src/tokens.generated.scss';
const TS = 'tokens/coolms-tokens.ts';
const HEADER = `GENERATED by tools/design-tokens.mjs from ${SOURCE} -- do not edit; edit the token file and regenerate.`;

/** The token file was read and something in it is wrong: a FOUND, never an "could not run". */
class Refused extends Error {
    constructor(reasons) {
        super('refused, nothing written:\n  ' + reasons.join('\n  '));
    }
}

/** The admin's brand accent: the app's accent is the server's, so its module leaves these out. */
const ADMIN_BRAND = /^accent(-|$)/;

/** `{cms.surface-muted}` -> `surface-muted`, or null for a literal value. */
function referenceOf(value) {
    const m = /^\{cms\.([a-z0-9-]+)\}$/.exec(value);
    return m ? m[1] : null;
}

/** surface-muted -> surfaceMuted */
function camel(key) {
    return key.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

export function generate(file) {
    const tokens = file?.cms;
    if (!tokens || typeof tokens !== 'object') {
        throw new Error(`${SOURCE} has no "cms" group`);
    }
    const refused = [];
    for (const [key, token] of Object.entries(tokens)) {
        const ext = token.$extensions?.['org.coolms'] ?? {};
        const reference = referenceOf(token.$value);
        if (reference !== null && !(reference in tokens)) {
            refused.push(`cms.${key} refers to cms.${reference}, which the file does not define`);
        }
        if (token.$type === 'color' && reference === null && !('dark' in ext) && !ext.invariant) {
            refused.push(`cms.${key} is a colour with neither a dark value nor a stated reason it does not flip`);
        }
    }
    if (refused.length) {
        throw new Refused(refused);
    }

    const css = (key, value) => {
        const reference = referenceOf(value);
        return `    --cms-${key}: ${reference === null ? value : `var(--cms-${reference})`};`;
    };
    const lightLines = [];
    const darkLines = [];
    for (const [key, token] of Object.entries(tokens)) {
        lightLines.push(css(key, token.$value));
        const dark = token.$extensions?.['org.coolms']?.dark;
        if (dark !== undefined) {
            darkLines.push(css(key, dark));
        }
    }
    const scss = `// ${HEADER}\n:root {\n${lightLines.join('\n')}\n}\n\n:root[data-theme='dark'] {\n${darkLines.join('\n')}\n}\n`;

    const light = {};
    const dark = {};
    const radius = {};
    for (const [key, token] of Object.entries(tokens)) {
        if (referenceOf(token.$value) !== null) {
            continue;
        }
        if (token.$type === 'color' && !ADMIN_BRAND.test(key)) {
            const ext = token.$extensions?.['org.coolms'] ?? {};
            light[camel(key)] = token.$value;
            dark[camel(key)] = 'dark' in ext ? ext.dark : token.$value;
        }
        const r = /^radius(-([a-z]+))?$/.exec(key);
        if (r && token.$type === 'dimension') {
            const px = /^(\d+(\.\d+)?)px$/.exec(token.$value);
            if (!px) {
                throw new Error(`cms.${key} is a radius that is not in px: ${token.$value}`);
            }
            radius[r[2] ?? 'default'] = Number(px[1]);
        }
    }
    const object = (o) => '{\n' + Object.entries(o).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n') + '\n}';
    const ts = `// ${HEADER}\n`
        + '// Plain data, no runtime: colours as React Native parses them, radii in px as numbers.\n\n'
        + `export const light = ${object(light)} as const;\n\n`
        + `export const dark = ${object(dark)} as const satisfies Record<keyof typeof light, string>;\n\n`
        + `export const radius = ${object(radius)} as const;\n\n`
        + 'export type ColourToken = keyof typeof light;\n';
    return { [SCSS]: scss, [TS]: ts };
}

try {
    const outputs = generate(JSON.parse(readFileSync(join(root, SOURCE), 'utf8')));
    if (process.argv.includes('--check')) {
        const stale = [];
        for (const [path, content] of Object.entries(outputs)) {
            let current = null;
            try {
                current = readFileSync(join(root, path), 'utf8');
            } catch {
                // absent: stale
            }
            if (current !== content) {
                stale.push(path);
            }
        }
        if (stale.length) {
            console.log(`FOUND -- ${stale.length} of ${Object.keys(outputs).length} generated file(s) are not what ${SOURCE} generates: ${stale.join(', ')}. Run: node tools/design-tokens.mjs`);
            process.exit(1);
        }
        console.log(`CLEAR -- ${Object.keys(outputs).length} of ${Object.keys(outputs).length} generated files are current`);
        process.exit(0);
    }
    for (const [path, content] of Object.entries(outputs)) {
        writeFileSync(join(root, path), content);
    }
    console.log(`written: ${Object.keys(outputs).join(', ')}`);
} catch (error) {
    if (error instanceof Refused) {
        console.log('FOUND -- ' + error.message);
        process.exit(1);
    }
    console.log('UNEVALUABLE -- ' + error.message);
    process.exit(2);
}
